[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \__pycache__
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''